services:
  db:
    image: postgres:16-alpine
    container_name: sixpath_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/init_db/table_creation.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - sixpath_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sixpath_user -d sixpath"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: sixpath_backend
    environment:
      # Database configuration
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # JWT configuration
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      # API configuration
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - "8000:8000"
    networks:
      - sixpath_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: deepblue597/sixpath-frontend:latest
    container_name: sixpath-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${API_BASE_URL}
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/frontend/Dockerfile
  #   container_name: sixpath_frontend
  #   environment:
  #     # Backend API URL
  #     API_BASE_URL: ${API_BASE_URL}
  #     # Streamlit configuration
  #     STREAMLIT_SERVER_PORT: ${STREAMLIT_SERVER_PORT}
  #     STREAMLIT_SERVER_ADDRESS: ${STREAMLIT_SERVER_ADDRESS}
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - sixpath_network
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  sixpath_network:
    driver: bridge
